### ISSUE TITLE
[Enhancement] Support for Flutter 3.10.0

### ISSUE THREAD

**Issue by ps6067966** [LeGoffMael/insta_assets_picker#11]
wechat_assets_picker: ^8.5.0

to support flutter latest stable version 3.10.0, please upgrade wechat_assets_picker package to 8.5.0

as Flutter community have done incredible work in 3.10.0 like impeller engine support in stable channel in ios, performance improvement, fast page load time in flutter web. 

Thank you.

**Comment by RoyalCoder88** [comment]
Also on Flutter 3.10.0 it's a problem with the dependency package "insta_assets_crop" 0.0.1 we are not able to build the app, because of the error:

`error ios flutter 3.10.0
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/insta_assets_crop-0.0.1/lib/src/crop.dart:112:68: Error: The class 'Drag' can't be used as a mixin because it isn't a mixin class nor a mixin.`

*also problem is the same for Android


thanks in advance

**Comment by LeGoffMael** [comment]
3.10.0 is now supported in the latest `1.4.0`.
